const ACCESS_TOKEN_EXPIRES_IN = process.env.ACCESS_TOKEN_EXPIRES_IN!;
const REFRESH_TOKEN_EXPIRES_IN = process.env.REFRESH_TOKEN_EXPIRES_IN!;
const WEB_PUSH_PUBLIC_KEY = process.env.WEB_PUSH_PUBLIC_KEY!;
const WEB_PUSH_PRIVATE_KEY = process.env.WEB_PUSH_PRIVATE_KEY!;
const WEB_PUSH_EMAIL = process.env.WEB_PUSH_EMAIL!;
const ACCESS_TOKEN_SECRET_KEY = process.env.ACCESS_TOKEN_SECRET_KEY!;
const REFRESH_TOKEN_SECRET_KEY = process.env.WEB_PUSH_EMAIL!;

export {
    WEB_PUSH_PUBLIC_KEY,
    WEB_PUSH_PRIVATE_KEY,
    WEB_PUSH_EMAIL,

    ACCESS_TOKEN_SECRET_KEY,
    ACCESS_TOKEN_EXPIRES_IN,
    REFRESH_TOKEN_SECRET_KEY,
    REFRESH_TOKEN_EXPIRES_IN,
}